### ISSUE TITLE
Test for native support using typeof

### ISSUE THREAD

**Issue by dwelle** [miguelmota/Navigator.sendBeacon#17]
So that we can polyfill sendBeacon even in browsers that *do* have native support, but the testing environment doesn't like it (e.g. [cypress](https://github.com/cypress-io/cypress/issues/687#issuecomment-459074801)).

This is how we'd polyfill it in cypress, if the support detection was done via `typeof navigator.sendBeacon === "function"`:

```js
cy.window().then(win => {
    win.navigator.sendBeacon = undefined;
    return new Promise( resolve => {
        win.document.querySelector("head").appendChild(
            Object.assign( win.document.createElement("script"), {
                onload: resolve,
                // https://github.com/miguelmota/Navigator.sendBeacon
                src: "https://unpkg.com/navigator.sendbeacon"
            })
        );
    });
});
```

I can issue a PR.

**Comment by miguelmota** [comment]
Closed via https://github.com/miguelmota/Navigator.sendBeacon/commit/882a7dbb34592fe987f131fd8f899eeca1e2fac4

**Comment by dwelle** [comment]
:100:

**Comment by dwelle** [comment]
This is embarrassing, because I haven't checked the code until now :). Your fix is checking whether the `navigator` is a function, but we need to check whether the `navigator.sendBeacon` is a function (in the `isSupported` helper). I'll make a PR.

**Comment by miguelmota** [comment]
@dwelle yea that was an error on my part but it was immediately fixed right away in the next commit. 

Thanks for removing the unnecessary checks. Merging!
