### ISSUE TITLE
Use XDomainRequest instead of ActiveXObject

### ISSUE THREAD

**Issue by isocroft** [miguelmota/Navigator.sendBeacon#18]
Since this package makes use of this line - ( `xhr.withCredentials = true;` ) in the polyfill script on line 19

It would be better to use `new XDomainRequest()` than `new ActiveXObject('Microsoft.XMLHTTP')` on line 17

I hope you see reason with me

Thanks

**Comment by miguelmota** [comment]
@isocroft XDomainRequest is [obsolete](https://developer.mozilla.org/en-US/docs/Web/API/XDomainRequest) and replaced by XMLHttpRequest  in Internet Explorer 10+

**Comment by miguelmota** [comment]
If this is a major issue I'm happy to merge in a pull request but I don't see the problem considering IE 8 and 9 are almost a decade old

**Comment by isocroft** [comment]
Alright.... l'll send a PR (sorry, Africa still has XP / Vista hanging around)
