### ISSUE TITLE
ES6 Import fails because package name contains dot character

### ISSUE THREAD

**Issue by detj** [miguelmota/Navigator.sendBeacon#2]
When using Babel/ES6, this fails

```
import 'navigator.sendbeacon';
```

Correct me If I'm wrong, I think this happens because the import thinks its a file because of the dot character.

Is there a way to fix this. I'm also using webpack but couldn't find a way to configure it. Is removing the `.` from the package name an option ?

**Comment by miguelmota** [comment]
@detj do you mind posting your babel script?

Works for me by doing:

``` bash
import sendBeacon from 'navigator.sendbeacon';

sendBeacon('http://example.com');
```

``` bash
$ babel index.js > out.js
$ browserify out.js > dist.js
```

I also fixed an invalid path in `package.json` so try using the latest.

**Comment by detj** [comment]
The path fix has fixed the issue. Thanks
