### ISSUE TITLE
Bower naming and versioning

### ISSUE THREAD

**Issue by jomehmet** [miguelmota/Navigator.sendBeacon#3]
The command `bower install navigator.sendbeacon` doesn't work.
You have named it Navigator.sendBeacon and bower install is case sensitive, perhaps you could rename it to lowercase?

https://github.com/bower/spec/blob/master/json.md#name
->Should be Lowercase, a-z

It's no support for other version than \* in bower since there are no tag on your commits.
Please add a tag with the version number to the latest commit on master.
https://github.com/bower/spec/blob/master/json.md#version

Nice contribution btw :+1:

**Comment by miguelmota** [comment]
Tagged and renamed. Thank you!
