### ISSUE TITLE
withCredentials not being set on XHR

### ISSUE THREAD

**Issue by Shervanator** [miguelmota/Navigator.sendBeacon#6]
Hi! I just noticed in the fallback case `xhr.withCredentials` is not being set, and specifically its not being set to true.

From all my testing `navigator.sendBeacon` is sending through the cookies on the domain, so to make this behaviour more consistent shouldn't the XHR fallback also send the cookies through?

**Comment by miguelmota** [comment]
fixed in https://github.com/miguelmota/Navigator.sendBeacon/pull/7

@Shervanator thanks for reporting

**Comment by Shervanator** [comment]
Thanks!
