### ISSUE TITLE
ES6: Always return native sendBeacon if it is available

### ISSUE THREAD

**Issue by jonathansp** [miguelmota/Navigator.sendBeacon#8]
By using ```import sendBeacon from 'navigator.sendbeacon'```, library should return browser's native `sendBeacon` function instead of its `sendBeacon`.

Actually, it'd be nice if we could use like as `core-js` does, since it is a polyfill. Importing `core-js/fn/math/trunc` polyfills `Math.trunc` if it is missing.

**Comment by miguelmota** [comment]
@jonathansp great suggestion; it's now using native function if supported.

**Comment by jonathansp** [comment]
Last version introduce a bug. I've been receiving `illegal invocation`. It's not working. Maybe you should `bind` navigator before returning `sendBeacon`. To reproduce this problem: 

```
import sendBeacon from 'navigator.sendbeacon'

sendBeacon(url, jsonObject)
```
Tested on chrome latest, macox, webpack 3.

**Comment by miguelmota** [comment]
@jonathansp it's bounded to navigator object now, see if that helps
