### ISSUE TITLE
make the fallback async unless onunload was called.

### ISSUE THREAD

**Issue by Nemo64** [miguelmota/Navigator.sendBeacon#9]
`sendBeacon` can be used outside the onunload event too. In those cases, using async:false is a really bad idea. 

Is there some reason not to make the request async by default and than switch to synchronous when onunload is fired?

Something like this:
```JavaScript
var async = true;
window.addEventListener('unload', function () {
    async = false;
});
[...]
xhr.open('POST', url, async);
```

This implementation has an ordering problem since the unload event has to be set before the unload event that is calling `sendBeacon`. But this is more a question.

**Comment by hax** [comment]
I think it's possible.

When `unload` is  fired, we can check the async `xhr`s, if they are not finished, we just `abort()` them and resend them with `async=false`.

Note, even an async xhr not have response yet, it may already reach the server, that means it have a chance a request could be sent twice, so we may also need some mechanism (eg. unique request ID) which let server-side filter out the repeated requests.

**Comment by nicjansma** [comment]
I second this.  As part of [Boomerang](https://github.com/akamai/boomerang), we use `sendBeacon()` and fall back to XHR/Images to send performance data.  This beaconing happens at `onload` and other parts during the normal page lifecycle, so calls to `sendBeacon()` in older browsers are basically forcing synchronous XHRs.

Agreed on @Nemo64 's solution and concern about the "ordering" problem, but IMO it's much better than having sync XHRs during onload!

**Comment by cvazac** [comment]
Workaround for users of this polyfill to force it to async XHR excepting the `unload` case (which itself is racy):
https://gist.github.com/cvazac/bfdb71ecfe610656aaf3bca596a51e47

**Comment by miguelmota** [comment]
Fixed in https://github.com/miguelmota/Navigator.sendBeacon/pull/10
